### ISSUE TITLE
Add bouncing ball with air friction model

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityBenchmarks#114]
The hybrid automaton for the bouncing ball with air friction (represented by a quadratic term in the velocity) is:

<img width="636" alt="Screen Shot 2019-03-22 at 11 00 12" src="https://user-images.githubusercontent.com/12424594/54827899-c7595480-4c91-11e9-9a78-8b072e479410.png">

See Example 4.1.2 page 98 in https://www.cs.colorado.edu/~xich8622/papers/thesis.pdf

**Comment by schillic** [comment]
Closed in #134.

**Comment by Aadesha** [comment]
![Screenshot 2019-04-04 at 10 51 47 PM](https://user-images.githubusercontent.com/29518290/55737653-392bef00-5a43-11e9-8471-e8decd3b1627.png)

**Comment by Aadesha** [comment]
![Screenshot 2019-04-09 at 7 46 39 PM](https://user-images.githubusercontent.com/29518290/55820091-e708cd80-5b17-11e9-99d5-8a8c257cbca4.png)
