### ISSUE TITLE
Performance issues with HSCC 2020 models

### ISSUE THREAD

**Issue by kostakoida** [JuliaReach/ReachabilityBenchmarks#158]
To run models you can run the following script: https://github.com/JuliaReach/ReachabilityBenchmarks/blob/hscc2020re/models/SpaceEx/hsccScript.jl

**Comment by kostakoida** [comment]
I think I should move the script. Should I create HSCC 2020 folder or separate repo as it was for ARCH RE?

**Comment by schillic** [comment]
> I think I should move the script. Should I create HSCC 2020 folder or separate repo as it was for ARCH RE?

I prefer to have the repository for repeatability packages clean, so let us keep it here for now until we are happy with the results.
