### ISSUE TITLE
Add ARCH18 Benchmarks

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityBenchmarks#17]
Add benchmark set for [ARCH COMP 2018](https://cps-vo.org/group/ARCH/FriendlyCompetition), category Continuous and Hybrid Systems with Linear Continuous Dynamics.

- [x] Building (problem from ARCH17)
- [x] Platooning (problem from ARCH17)
- [x] Gearbox (problem from ARCH17)
- [x] International space station https://cps-vo.org/node/48401
- [x] Spacecraft rendevouz https://easychair.org/publications/open/S2V

<del>- [ ] Gearbox example http://stanleybak.com/papers/bak2017formats.pdf<del>
<del>- [ ] Drivedrain https://cps-vo.org/node/49114 <del>

See also ARCH 2017 report: https://easychair.org/publications/open/X6

**Comment by nikos-kekatos** [comment]
The drivetrain and gearbox links correspond to the same model. Is that the case?

**Comment by nikos-kekatos** [comment]
i am not certain if the space station model described in https://cps-vo.org/node/48401 is the same with the benchmark https://cps-vo.org/node/26546.

**Comment by nikos-kekatos** [comment]
Ok, I think that they look fine but they need to be flattened.

**Comment by nikos-kekatos** [comment]
same for drivetrain models.

**Comment by nikos-kekatos** [comment]
@mforets for platooning you probably refer to the benchmark of [2014](https://cps-vo.org/node/12115), not 2017.

**Comment by mforets** [comment]
> The drivetrain and gearbox links correspond to the same model. Is that the case?

for gearbox i have this link: http://stanleybak.com/papers/bak2017formats.pdf 
but i wasn't able to find the model

for Drivedrain there is this thread with the model: https://cps-vo.org/node/49114

**Comment by nikos-kekatos** [comment]
most probably they refer to this one https://cps-vo.org/node/12109!

**Comment by nikos-kekatos** [comment]
so the old building models have an error with the controlled variable y1. The new building models are fine and they are parsed. I use the ones from the [forum](https://cps-vo.org/node/30277).

**Comment by schillic** [comment]
> the old building models have an error with the controlled variable y1

What are the old models? Do you mean the ones [in this repo](https://github.com/JuliaReach/ReachabilityBenchmarks/tree/master/models/SLICOT/building)? What is the error, wrong syntax or wrong numbers?

**Comment by nikos-kekatos** [comment]
I was referring to the old models in the ARCH [repository](https://cps-vo.org/node/34059). 

Quickly checking your building models they look fine! 

The error was related to controlled/uncontrolled variables. Actually, it is quite a common error that we have come across. So if you have an algebraic equation in the invariant of a location, e.g. y==c*x, then this variable (y) should be uncontrolled. In most cases, peole put it as controlled. Most of the times, this error does not cause any issues (but it depends on the model itself).

**Comment by nikos-kekatos** [comment]
so now all the models have been uploaded.
