### ISSUE TITLE
Add RE model for HSCC 2019

### ISSUE THREAD

**Issue by kostakoida** [JuliaReach/ReachabilityBenchmarks#32]
settings:
- remove :partition option (default = 1D, what we want)
- choose T such that the fixpoint is detected, but not much beyond 
that (should be an integer, though)
- choose δ such that the plots look okay
- choose ε_proj such that the plots look okay
- remove :fixpoint_check option (default = :eager, what we want)
- remove :clustering option (default = :chull, what we want)
- in the end deactivate :verbosity (but keep the option for debugging)

about script:
- goal: we (and the reviewer) run this script with a single command over night; no user interaction needed; *results are stored to a file*
- make n0 and post operators an input parameter, default to 2 and the 
operators as you like
- wrap the model in a function, e.g., filtered_oscillator(n0, opC, opD)
- benchmark script: run a loop for n0 = 2, 4, 8, ...
- `include`s the model file, then calls the function in a loop
- always perform a warm-up run, then perform a second run
- have different upper bounds for different post operators (e.g.,  concrete: n0 = 4(?)), after which you do not include them anymore
- write results file continuously after each successful run - we do 
not want to interrupt after 5h and have no result at all
- after each run of the script, the output file should change (add an index to old or new file, choose the file name as the current date/time, whatever)

test this script:
- [ ] interrupt it and see if you can restart it 
- [ ] see if it writes partial results 
- [ ] see if it overwrites old results  
- [ ]  see if all operators work 
- [ ] specify a low upper bound for all of 
them to test

**Comment by mforets** [comment]
this is done, isn't it? 

if not, shall we split the TO-DO's in smaller issues?

let me add to the list: *outsource `HSCC2019_RE` to its own repo.*

**Comment by schillic** [comment]
Yes, these tasks are not needed anymore. I will create a new issue for the oursourcing.
