### ISSUE TITLE
Outsource HSCC2019 models to a new repo

### ISSUE THREAD

**Issue by schillic** [JuliaReach/ReachabilityBenchmarks#39]
See [this comment](https://github.com/JuliaReach/ReachabilityBenchmarks/issues/32#issuecomment-433078193).
I am not sure about outsourcing in the sense of moving. I think we still want to have that benchmark here.

**Comment by mforets** [comment]
the repository https://github.com/JuliaReach/ARCH2018_RE can serve as a template

**Comment by mforets** [comment]
on my wishlist: add a *video* explaining how to install and run that RE.

**Comment by schillic** [comment]
We have https://github.com/JuliaReach/HSCC2019_RE, but it is still empty.
Before we outsource, we should fix #50 and check if everything still works.
