### ISSUE TITLE
Add parametric powertrain model (ARCH2018 AFF)

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityBenchmarks#41]
Add parametric powertrain model:

http://www.i6.in.tum.de/Main/Publications/Althoff2012a.pdf

https://www.researchgate.net/profile/Adam_Lagerberg/publication/251989348_A_Benchmark_on_Hybrid_Control_of_an_Automotive_Powertrain_with_Backlash/links/555ef93708ae86c06b5f685c/A-Benchmark-on-Hybrid-Control-of-an-Automotive-Powertrain-with-Backlash.pdf

**Comment by schillic** [comment]
Closed in #112.
