### ISSUE TITLE
Review SLICOT models and bench script 

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityBenchmarks#5]
## SLICOT

- [x] beam
- [x] building
- [x] cdplayer
- [x] fom
- [x] heat
- [x] iss
- [x] mna1
- [x] mna5
- [x] motor
- [x] pde

**Comment by mforets** [comment]
for the SLICOT benchmarks we can put back the `plot_polygon` that directly uses `PyPlot`. this can be done as a function in the `/src`. reason: at the moment, for large number of sets and the current setup i obtain a dark-colored flowpipe. also for exact reproducibility of the reported results.

**Comment by schillic** [comment]
We should also change the warm-up command such that it restricts `δ` to the default value and `N` to 3.
Reason: For bad choices of `δ` we get `NaN` problems.

**Comment by schillic** [comment]
The SLICOT models have been revised in #13.

**Comment by schillic** [comment]
We should wrap the `Plotting...` output in `info` blocks and, if possible, use `tocc()` there.

**Comment by schillic** [comment]
> MNA5 still needs to be revised: The HPolygon analysis crashes with an odd dimension.

Possible fix: add `:block_types=>Dict(HPolygon=>[(2*i-1:2*i) for i in 1:5456], Interval=>[10913:10913])` to the `HPolygon` analysis
@mforets: What do you think?

**Comment by mforets** [comment]
> What do you think?

ok.

**Comment by mforets** [comment]
Done

**Comment by mforets** [comment]
CLose?
