### ISSUE TITLE
Spacecraft rendezvous benchmark

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityBenchmarks#59]
This is a spacecraft rendezvous use case of hybrid systems with nonlinear dynamics that was used in [ARCH18-NLN](https://easychair.org/publications/paper/gjfh). I didn't yet find the .sx model files. Maybe we have to write the model from scratch in Julia.

The nonlinear dynamic equations describe the two-dimensional, planar motion of the spacecraft on an orbital plane towards a space station. The hybrid nature of this benchmark origins from a switched controller. The specifications that have to be satisfied involve a line-of-sight condition in the rendezvous attemp mode; collision avoidance in the aborting mode; and finally a velocity constraint specification in the rendezvous attempt mode.

**Comment by schillic** [comment]
See https://github.com/JuliaReach/ReachabilityBenchmarks/pull/78 for the linearized model.

**Comment by mforets** [comment]
CC: @lbenet, @dpsanders

```julia
julia> include("models/ARCH/NLN/SpacecraftRendezvous/spacecraft_rendezvous.jl")
[warn | Reachability]: Several option aliases were used for aliases Symbol[:check_invariant_intersection].
ERROR: LoadError: Error: it cannot prove existence and unicity of the solution
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] remainder_taylorstep(::getfield(Main, Symbol("##3#5")), ::Taylor1{Float64}, ::Array{Taylor1{TaylorN{Float64}},1}, ::Array{Taylor1{TaylorN{Float64}},1}, ::Array{Taylor1{In
tervalArithmetic.Interval{Float64}},1}, ::Array{Taylor1{IntervalArithmetic.Interval{Float64}},1}, ::IntervalArithmetic.IntervalBox{5,Float64}, ::IntervalArithmetic.Interval{Fl

oat64}) at /Users/forets/.julia/packages/TaylorModels/79LT9/src/validatedODEs.jl:59
```

**Comment by lbenet** [comment]
Maybe this is not the place to report this, but I think [here](https://github.com/JuliaReach/ReachabilityBenchmarks/blob/master/models/ARCH/NLN/SpacecraftRendezvous/spacecraft_rendezvous.jl#L7) it should be `TaylorModels` instead of `TaylorIntegration`.

**Comment by mforets** [comment]
I think it's good since `@taylorize` is from `TaylorIntegration`. `TaylorModels` is loaded internally by Reachability. (cf. https://github.com/JuliaReach/ReachabilityBenchmarks/pull/121 for Van der Pol; ill merge it asap, sorry...)

**Comment by schillic** [comment]
The model was added and the competition is over. We could not analyze the model, but future attempts should be collected in a new issue.
