### ISSUE TITLE
Put back setup with PyPlot

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityBenchmarks#8]
proposal: for the SLICOT reachability benchmarks, put back the setup with PyPlot. keep the general setup using Plots for other cases, and for notebooks.

**Comment by schillic** [comment]
Can you give a motivation?

**Comment by mforets** [comment]
to reproduec the plots from https://arxiv.org/abs/1801.09526  , because with GR they appear black and the quality is not that nice. i don't have a clue of this behavior. maybe there is a better setup for this use case (GLVisualize? MakiE?), where we want to plot thousands of polygons.

**Comment by mforets** [comment]
do you remember how much time did it take for 20k sets? it was around 15 minutes?

**Comment by schillic** [comment]
I assume that we just have to change the color of the border.

**Comment by schillic** [comment]
>  do you remember how much time did it take for 20k sets?

No, but I can test tomorrow.

**Comment by mforets** [comment]
also asked [here](https://discourse.julialang.org/t/plotting-thousands-of-polygons/9066).

**Comment by schillic** [comment]
> do you remember how much time did it take for 20k sets?

I tested with the motor model.
Here it takes 40 seconds (with Plots/GR) (I ran the version in master; I think this corresponds to 20k sets).
The old version (with the old code base and PyPlot) takes 276 seconds here.

This is a surprising speedup!
Did we change other things, e.g., is the input to `plot` still the same?
Did it really take 15 minutes for you or was this just a guess?

**Comment by mforets** [comment]
would you mind trying after pulling `Reachability` from master?? i want to see if it takes < 2sec ! (in the second run as usual)

PS: for me it took in the order of 10 minutes in the past 20k sets, but maybe this number of for the old code base.

**Comment by schillic** [comment]
almost, 2.192668595 seconds :)

**Comment by mforets** [comment]
and the color?

**Comment by schillic** [comment]
blue, but see my comment [here](https://github.com/JuliaReach/Reachability.jl/issues/66#issuecomment-366234539)

**Comment by schillic** [comment]
Should we close this one? I think we do not want PyPlot anymore...
