### ISSUE TITLE
Laub-Loomis benchmark using TMJets

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityBenchmarks#83]
cc: @lbenet 

From #67:

```julia
julia> include("models/ARCH/NLN/LaubLoomis/laubloomis_benchmark.jl")
(1/1) benchmarking "LaubLoomis"...
  (1/2) benchmarking "W=0.01"...
  done (took 6.740568393 seconds)
  (2/2) benchmarking "W=0.1"...
  done (took 6.274265459 seconds)
done (took 13.547741628 seconds)

minimum time for each benchmark:
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "LaubLoomis" => 2-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "W=0.01" => TrialEstimate(1.521 s)
          "W=0.1" => TrialEstimate(1.119 s)
median time for each benchmark:
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "LaubLoomis" => 2-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "W=0.01" => TrialEstimate(1.533 s)
          "W=0.1" => TrialEstimate(1.131 s)
```

![screen shot 2019-02-28 at 14 40 41](https://user-images.githubusercontent.com/12424594/53586682-74dfb900-3b67-11e9-9594-f601985ede9d.png)

The blue line does goe *outside* the reach pipe. But i guess this is just that the simulation uses a step size that is too big; i'll try by plotting in the same pair of axes `xTM` (with the benchmark params: `abs_tol=1e-6, orderT=8, orderQ=2`) and a simulation with a smaller time step.

Note how the accuracy improves using `abs_tol=1e-18, orderT=12, orderQ=2`:

![screen shot 2019-02-28 at 14 48 10](https://user-images.githubusercontent.com/12424594/53586983-123aed00-3b68-11e9-9157-c3f53ee6f5ab.png)

**Comment by mforets** [comment]
How do we explain the phenomenon around time 14 sec for the benchmark settings? I think this is the [online refinement loop](https://github.com/JuliaIntervals/TaylorModels.jl/pull/18/files#diff-0b1e39ec90fd8e8effb5d387244adf11R148). Perhaps we can count the number of times we had to refine, for information.

**Comment by lbenet** [comment]
I've been playing with this, and noticed the effect that you are reporting. As you say, when the step size is "too big", the overestimation becomes important, though once the "step size" is properly rescaled, things behave correctly again.

though the simulation is slower, I prefer the behavior of using larger `orderT` values and smaller `abs_tolerance`, as in the second plot.

**Comment by lbenet** [comment]
> How do we explain the phenomenon around time 14 sec for the benchmark settings? I think this is the [online refinement loop](https://github.com/JuliaIntervals/TaylorModels.jl/pull/18/files#diff-0b1e39ec90fd8e8effb5d387244adf11R148). Perhaps we can count the number of times we had to refine, for information.

I have no explanation yet for that, but as said above, some over-estimations accumulate, which are the properly handled once the time-step is reduced.

**Comment by mforets** [comment]
With the last commit in [valdatedODEs](https://github.com/JuliaIntervals/TaylorModels.jl/pull/18), the benchmark settings are no longer valid over the given time horizon,

```julia
julia> include("models/ARCH/NLN/LaubLoomis/laubloomis_benchmark.jl")
ERROR: LoadError: Error: it cannot prove existence and unicity of the solution
```

And the default settings pass in

```julia
julia> @btime laubloomis_TMJets();
  17.858 s (151467940 allocations: 10.36 GiB)
```

**Comment by lbenet** [comment]
Can you please mention the parameters you are using for the integration that does not work? 

The following parameters give reasonable results:
- For `W=0.01`: `abs_tol = 1.0e-18`, `orderT  = 12`, `orderQ  = 2`
- For `W=0.1`: `abs_tol = 1.0e-24`, `orderT = 16`, `orderQ = 2`

**Comment by mforets** [comment]
The ones in the [benchmark script](https://github.com/JuliaReach/ReachabilityBenchmarks/blob/master/models/ARCH/NLN/LaubLoomis/laubloomis_benchmark.jl#L14), which verified the property previously.

Thanks for sending the new parameters. I'll make update `laubloomis_benchmark.jl` accordingly.

**Comment by mforets** [comment]
>  Thanks for sending the new parameters. I'll update `laubloomis_benchmark.jl` accordingly

Done. The results are:

```julia
julia> include("models/ARCH/NLN/LaubLoomis/laubloomis_benchmark.jl")
(1/1) benchmarking "LaubLoomis"...
  (1/2) benchmarking "W=0.01"...
  done (took 13.483893198 seconds)
  (2/2) benchmarking "W=0.1"...
  done (took 19.510441722 seconds)
done (took 33.52159346 seconds)
minimum time for each benchmark:
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "LaubLoomis" => 2-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "W=0.01" => TrialEstimate(12.932 s)

          "W=0.1" => TrialEstimate(18.972 s)
median time for each benchmark:
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "LaubLoomis" => 2-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "W=0.01" => TrialEstimate(12.932 s)
          "W=0.1" => TrialEstimate(18.972 s)
```

**Comment by mforets** [comment]
Update for the latest commits in [TaylorModels](https://github.com/JuliaIntervals/TaylorModels.jl/pull/18): the property is no longer valid with the benchmark options,

```julia
𝑂₁ = Options(:t0=>0.0, :T=>20.0, :W=>0.01, :abs_tol=>1e-18,
              :orderT=>12, :orderQ=>2, :maxsteps=>1000, :property=>(t,x)->x[4] < 4.5)

julia> include("models/ARCH/NLN/LaubLoomis/laubloomis_benchmark.jl")
ERROR: LoadError: Error: it cannot prove existence and unicity of the solution
Stacktrace:
 [1] error(::String) at ./error.jl:33
```

@lbenet could you double check, please?

**Comment by lbenet** [comment]
Can you try it with `orderT=9`, `abs_tol=1.0e-13`? 

Locally I get something around 10 sec, which is a factor around 2 slower... There are other combinations that work too, but I haven't been able to improve the timing...

**Comment by lbenet** [comment]
I have look again into this; the following parameters yield better results: `abs_tol = 1.0e-10`, `orderT = 7`, `orderQ = 2`. For `W=0.01` the elapsed time is ~9 sec, while the same parameters for `W=0.1`yield ~10 sec.

**Comment by mforets** [comment]
Very good. I've updated the parameters with those values. I get

```julia
julia> include("models/ARCH/NLN/LaubLoomis/laubloomis_benchmark.jl")
(1/1) benchmarking "LaubLoomis"...
  (1/2) benchmarking "W=0.01"...
  done (took 9.318539306 seconds)
  (2/2) benchmarking "W=0.1"...
  done (took 9.249842795 seconds)
done (took 19.103946335 seconds)
minimum time for each benchmark:
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "LaubLoomis" => 2-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "W=0.01" => TrialEstimate(8.740 s)
          "W=0.1" => TrialEstimate(8.646 s)
median time for each benchmark:

1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "LaubLoomis" => 2-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "W=0.01" => TrialEstimate(8.740 s)
          "W=0.1" => TrialEstimate(8.646 s)
```

Plots look good:

### Case W = 0.01

<img width="580" alt="Screen Shot 2019-03-09 at 10 33 25" src="https://user-images.githubusercontent.com/12424594/54072236-e221d700-4256-11e9-9dd8-f29d8ee5efbe.png">



### Case W = 0.1


<img width="594" alt="Screen Shot 2019-03-09 at 10 35 52" src="https://user-images.githubusercontent.com/12424594/54072257-257c4580-4257-11e9-900f-6f8409ff1bab.png">

**Comment by mforets** [comment]
With #130,

- orderQ is set to 1 for the three cases
- we output the width of the final box
- we add the intermediate case W= 0.05

```julia
julia> include("models/ARCH/NLN/LaubLoomis/laubloomis_benchmark.jl")

width of final box, case W = 0.01 = 0.012189913655366702
width of final box, case W = 0.05 = 0.02975760040111819
width of final box, case W = 0.1 = 0.05035859438781731
(1/1) benchmarking "LaubLoomis"...
  (1/3) benchmarking "W=0.01"...
  done (took 7.511226626 seconds)
  (2/3) benchmarking "W=0.1"...
  done (took 7.499018246 seconds)
  (3/3) benchmarking "W=0.05"...
  done (took 7.151784425 seconds)
done (took 22.739915231 seconds)
minimum time for each benchmark:
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "LaubLoomis" => 3-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "W=0.01" => TrialEstimate(3.384 s)
          "W=0.1" => TrialEstimate(3.393 s)
          "W=0.05" => TrialEstimate(3.197 s)
median time for each benchmark:
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "LaubLoomis" => 3-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "W=0.01" => TrialEstimate(3.454 s)
          "W=0.1" => TrialEstimate(3.415 s)
          "W=0.05" => TrialEstimate(3.274 s)
```

![laubloomis_case_all](https://user-images.githubusercontent.com/12424594/55198512-08bb9980-5195-11e9-977e-7e5b6433111a.png)
