### ISSUE TITLE
Document `runall.jl` script

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityBenchmarks#9]
... to execute all SLICOT benchmarks.

We can explain the existent `benchmark_all.sh` script on the README.

**Comment by schillic** [comment]
`runall.jl` does not exist!?

**Comment by mforets** [comment]
I think this is correct, in [Usage](https://github.com/JuliaReach/ReachabilityBenchmarks#usage) and in [Running all the benchmarks](https://github.com/JuliaReach/ReachabilityBenchmarks#running-all-the-benchmarks). Also, navigating in the [src](https://github.com/JuliaReach/ReachabilityBenchmarks/tree/master/src) gives access to the documented benchmarking functions (for SLICOT models).

**Comment by mforets** [comment]
I think this is correct, in Usage and in Running all the benchmarks. Also, navigating in the src gives access to the documented benchmarking functions (for SLICOT models).

**Comment by mforets** [comment]
👍
