### ISSUE TITLE
Revise one_loop_iteration option in filtered-oscillator model

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityBenchmarks#91]
- Add docstring to `filtered_oscillator` (see https://github.com/JuliaReach/Reachability.jl/issues/536#issuecomment-471947051)
- Remove this option altogether and pass `max_jumps` through `options` instead? Is there any difference?

**Comment by schillic** [comment]
The point of this option was to have a fair comparison to SpaceEx, which does not offer a `max_jump` option.

**Comment by mforets** [comment]
Ok, i see. I think that we just need to attach a docstring to the model and document all this.
